name: build test sign

on:
  schedule:
    # schedule build every night
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/msbuild.yml
    with:
      sign-mode: "Test Sign"
