name: build test sign

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/msbuild.yml
    with:
      sign-mode: "Test Sign"
