name: build sign off

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/msbuild.yml
    with:
      sign-mode: "off"
      upload-tag: "build_github_ci_sign_off"
