name: Build driver solution
on:
  schedule:
      # schedule build every night
      - cron: "0 0 * * *"
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]
    runs-on: windows-2022
    env:
      Solution_Path: RustDeskIddDriver.sln
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build solution
        run: |
          set MSBuildUserExtensionsPath=%VSINSTALLDIR%\MsBuild
          msbuild ${{ env.Solution_Path }} -p:Configuration=${{ env.Configuration }} -p:Platform=${{ env.Platform }} /p:TargetVersion=Windows10
        env:
          Configuration: ${{ matrix.configuration }}
          Platform: ${{ matrix.platform }}

      - name: Zip files
        env:
          DIST_DIR: RustDeskIddDriver_${{ matrix.platform }}
        run: |
          mkdir -p ${{ env.DIST_DIR }}
          mv ./${{ matrix.platform }}/${{ matrix.configuration }}/RustDeskIddDriver ${{ env.DIST_DIR }}
          mv ./${{ matrix.platform }}/${{ matrix.configuration }}/RustDeskIddDriver.cer ${{ env.DIST_DIR }}
          mv ./${{ matrix.platform }}/${{ matrix.configuration }}/RustDeskIddApp.exe ${{ env.DIST_DIR }}
          mv ./RustDeskIddApp/README.md ${{ env.DIST_DIR }}
          Compress-Archive -Path ${{ env.DIST_DIR }}/* -Destination ${{ env.DIST_DIR }}.zip
          md5sum ${{ env.DIST_DIR }}.zip > ${{ env.DIST_DIR }}.zip.checksum_md5

      - name: Publish Release
        env:
          DIST_FILE: RustDeskIddDriver_${{ matrix.platform }}.zip
        uses: softprops/action-gh-release@v1
        if: always()
        with:
          prerelease: true
          tag_name: build_github_ci
          files: |
            ${{ env.DIST_FILE }}
            ${{ env.DIST_FILE }}.checksum_md5
