name: Build driver

on:
  workflow_call:
    inputs:
      sign-mode:
        type: string
        default: "Test Sign"

  push:
    branches:
      - main

env:
  Solution_Path: RustDeskIddDriver.sln
  Project_Driver: ./RustDeskIddDriver/RustDeskIddDriver.vcxproj
  Project_App: ./RustDeskIddApp/RustDeskIddApp.vcxproj

jobs:
  build-windows-test-sign:
    runs-on: ${{ matrix.target }}
    strategy:
        fail-fast: false
        matrix:
          target: [windows-2022]
          configuration: [Release]
          platform: [x64]
    env:
      Dist_Dir: RustDeskIddDriver_${{ matrix.platform }}
      Driver_Output_Dir: ./RustDeskIddDriver/${{ matrix.platform }}/${{ matrix.configuration }}
      App_Output_Dir: ./RustDeskIddApp/${{ matrix.platform }}/${{ matrix.configuration }}
      Configuration: ${{ matrix.configuration }}
      Platform: ${{ matrix.platform }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Try build driver test sign
        if: inputs.sign-mode == 'Test Sign'
        run: |
          msbuild ${{ env.Project_Driver }} -p:Configuration=${{ env.Configuration }} -p:Platform=${{ env.Platform }} /p:TargetVersion=Windows10

      - name: Try build driver sign off
        if: inputs.sign-mode == 'off'
        run: |
          msbuild ${{ env.Project_Driver }} -p:Configuration=${{ env.Configuration }} -p:Platform=${{ env.Platform }} /p:TargetVersion=Windows10 /p:SignMode=off

      - name: Build demo app
        run: |
          msbuild ${{ env.Project_App }} -p:Configuration=${{ env.Configuration }} -p:Platform=${{ env.Platform }} /p:TargetVersion=Windows10

    #   - name: Sign driver
    #     uses: GermanBluefox/code-sign-action@v7
    #     if: inputs.sign-mode == 'off'
    #     with:
    #       certificate: '${{ secrets.WINDOWS_PFX_BASE64 }}'
    #       password: '${{ secrets.WINDOWS_PFX_PASSWORD }}'
    #       certificatesha1: '${{ secrets.WINDOWS_PFX_SHA1_THUMBPRINT }}'
    #       folder: ./RustDeskIddDriver/${{ matrix.platform }}/${{ matrix.configuration }}
    #       recursive: false

      - name: Create dist dir
        run: |
          mkdir -p ${{ env.Dist_Dir }}

      - name: Copy cert file if test sign
        if: inputs.sign-mode == 'Test Sign'
        run: |
          mv ./${{ env.Driver_Output_Dir }}/RustDeskIddDriver.cer ${{ env.Dist_Dir }}

      - name: Zip files
        run: |
          mv ./${{ env.Driver_Output_Dir }}/RustDeskIddDriver ${{ env.Dist_Dir }}
          mv ./${{ env.App_Output_Dir }}/RustDeskIddApp.exe ${{ env.Dist_Dir }}
          mv ./RustDeskIddApp/README.md ${{ env.Dist_Dir }}
          Compress-Archive -Path ${{ env.Dist_Dir }}/* -Destination ${{ env.Dist_Dir }}.zip
          md5sum ${{ env.Dist_Dir }}.zip > ${{ env.Dist_Dir }}.zip.checksum_md5

      - name: Publish Release
        env:
          DIST_FILE: RustDeskIddDriver_${{ matrix.platform }}.zip
        uses: softprops/action-gh-release@v1
        if: always()
        with:
          prerelease: true
          tag_name: build_github_ci
          files: |
            ${{ env.DIST_FILE }}
            ${{ env.DIST_FILE }}.checksum_md5
