name: Build driver

on:
  workflow_call:
    inputs:
      sign-mode:
        type: string
        default: "Test Sign"

  push:
    branches:
      - main

env:
  Solution_Path: RustDeskIddDriver.sln
  Project_Driver: ./RustDeskIddDriver/RustDeskIddDriver.vcxproj
  Project_App: ./RustDeskIddApp/RustDeskIddApp.vcxproj

jobs:
  build-windows-test-sign:
    runs-on: ${{ matrix.target }}
    strategy:
        fail-fast: false
        matrix:
          target: [windows-2022]
          configuration: [Release]
          platform: [x64]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build driver
        run: |
          msbuild ${{ env.Project_Driver }} -p:Configuration=${{ env.Configuration }} -p:Platform=${{ env.Platform }} /p:TargetVersion=Windows10 /p:SignMode="${{ inputs.sign-mode }}"
        env:
          Configuration: ${{ matrix.configuration }}
          Platform: ${{ matrix.platform }}

      - name: Build demo app
        run: |
          msbuild ${{ env.Project_App }} -p:Configuration=${{ env.Configuration }} -p:Platform=${{ env.Platform }} /p:TargetVersion=Windows10
        env:
          Configuration: ${{ matrix.configuration }}
          Platform: ${{ matrix.platform }}

      - name: Zip files
        env:
          DIST_DIR: RustDeskIddDriver_${{ matrix.platform }}
        run: |
          mkdir -p ${{ env.DIST_DIR }}
          mv ./${{ matrix.platform }}/${{ matrix.configuration }}/RustDeskIddDriver ${{ env.DIST_DIR }}
          mv ./${{ matrix.platform }}/${{ matrix.configuration }}/RustDeskIddDriver.cer ${{ env.DIST_DIR }}
          mv ./${{ matrix.platform }}/${{ matrix.configuration }}/RustDeskIddApp.exe ${{ env.DIST_DIR }}
          mv ./RustDeskIddApp/README.md ${{ env.DIST_DIR }}
          Compress-Archive -Path ${{ env.DIST_DIR }}/* -Destination ${{ env.DIST_DIR }}.zip
          md5sum ${{ env.DIST_DIR }}.zip > ${{ env.DIST_DIR }}.zip.checksum_md5

      - name: Publish Release
        env:
          DIST_FILE: RustDeskIddDriver_${{ matrix.platform }}.zip
        uses: softprops/action-gh-release@v1
        if: always()
        with:
          prerelease: true
          tag_name: build_github_ci
          files: |
            ${{ env.DIST_FILE }}
            ${{ env.DIST_FILE }}.checksum_md5
